server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  output:
    ansi:
      enabled: always
  application:
    name: minio-upload
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  disable-i18n: true
  model-converters:
    pageable-converter:
      enabled: true
  show-actuator: false
  api-docs:
    groups:
      enabled: true